import { db } from "./db";

// Auto-generated by scripts/initiate-armies.js — do not edit by hand.
// Edit scripts/army-data.json, then run: npm run initiate-armies

// === ORDERS LISTS ===

const ORDERS_Raider_Orders = [
  "Move Forward 1",
  "Activate Targeting Map",
  "If Any Enemies in Range ...",
  "Move toward located Enemy",
  "If Any Enemies in Range ...",
  "Move toward located Enemy",
  "If Any Enemies in Range ...",
  "Fire All",
  "If Facing Off-Map ...",
  "Turn Left",
  "If Movement Blocked by Ally ...",
  "Veer Left",
  "Move Forward 1",
  "Move Forward 1",
];

const ORDERS_Trooper_Orders = [
  "Activate Targeting Map",
  "If Any Enemies in Range ...",
  "Fire All",
  "If Facing Off-Map ...",
  "Turn Left",
  "Veer Left",
  "Move Forward 3",
  "Activate Targeting Map",
  "If Any Enemies in Range ...",
  "Fire All",
  "If Facing Off-Map ...",
  "Turn Left",
  "Move Forward 1",
  "Move Forward 1",
  "Activate Targeting Map",
  "If Any Enemies in Range ...",
  "Fire All",
];

const ORDERS_Fortress_Orders = [
  "Activate Targeting Map",
  "If Movement Blocked by Enemy ...",
  "Fire Master Weapon",
  "If Movement Blocked by Enemy ...",
  "Fire Seconday Weapon",
  "If Movement Blocked by Ally ...",
  "Veer Left",
  "If Movement Blocked by Ally ...",
  "Veer Left",
  "If Movement Blocked by Ally ...",
  "Veer Left",
  "If Movement Blocked by Ally ...",
  "Veer Left",
  "If Movement Blocked by Ally ...",
  "Veer Left",
  "If Movement Blocked by Ally ...",
  "Turn Left",
  "Move Forward 1",
  "Move Forward 1",
  "Activate Targeting Map",
  "If Any Enemies in Range ...",
  "Fire Master Weapon",
  "If Facing Off-Map ...",
  "Turn Left",
  "If Facing Off-Map ...",
  "Veer Left",
  "Move Forward 1",
  "Move Forward 1",
  "If Facing Off-Map ...",
  "Veer Left",
];

const ORDERS_Jay_Orders = [
  "If Facing Off-Map ...",
  "Turn Right",
  "Activate Targeting Map",
  "If Any Enemies in Range ...",
  "Move toward located Enemy",
  "If Any Enemies in Range ...",
  "Activate Targeting Map",
  "If Any Enemies in Range ...",
  "Fire Master Weapon",
  "If Any Enemies in Range ...",
  "Fire Seconday Weapon",
  "Veer Left",
  "Move Forward 1",
  "Veer Right",
  "Move Forward 1",
];

const ORDERS_Speedy_Bot = [
  "If Facing Off-Map ...",
  "Turn Right",
  "Veer Right",
  "Move Forward 1",
  "Activate Targeting Map",
  "If Movement Blocked by Ally ...",
  "Veer Right",
  "If Movement Blocked by Ally ...",
  "Veer Right",
  "If Movement Blocked by Ally ...",
  "Veer Right",
  "If Movement Blocked by Ally ...",
  "Veer Right",
  "If Movement Blocked by Ally ...",
  "Veer Right",
  "Move Forward 1",
  "Move Forward 1",
  "Activate Targeting Map",
  "If Any Enemies in Range ...",
  "Fire Master Weapon",
  "If Any Enemies in Range ...",
  "Fire Seconday Weapon",
  "Activate Targeting Map",
  "If Any Enemies in Range ...",
  "Activate Self-Destruct",
  "If Facing Off-Map ...",
  "Veer Right",
];

// === TARGET MAP GRIDS ===

const MAP_Raider_Map: string[][] = [
  ["","","","","","",""],
  ["","10","4","2","6","8",""],
  ["","9","3","1","5","7",""],
  ["","13","11","","12","14",""],
  ["","23","17","15","19","21",""],
  ["","24","18","16","20","22",""],
  ["","","","","","",""],
];

const MAP_Trooper_Map: string[][] = [
  ["13","9","8","7","10","11","12"],
  ["15","14","5","2","6","16","17"],
  ["19","18","3","1","4","20","21"],
  ["27","26","25","","22","23","24"],
  ["34","33","28","29","30","38","39"],
  ["37","36","35","31","40","41","42"],
  ["48","47","46","32","43","44","45"],
];

const MAP_Fortress_Map: string[][] = [
  ["21","18","17","15","16","19","20"],
  ["14","13","4","2","6","9","10"],
  ["12","11","3","1","5","7","8"],
  ["26","24","22","","23","25","27"],
  ["33","32","29","28","30","31","34"],
  ["41","39","37","35","36","38","40"],
  ["47","45","43","42","44","46","48"],
];

const MAP_Speedy_Bomb: string[][] = [
  ["0","0","0","0","0","0","0"],
  ["0","0","0","0","0","0","0"],
  ["0","0","1","2","3","0","0"],
  ["0","0","4","","5","0","0"],
  ["0","0","6","7","8","0","0"],
  ["0","0","0","0","0","0","0"],
  ["0","0","0","0","0","0","0"],
];

// === SEED FUNCTION ===

export async function seedUserDefaults(userId: number): Promise<void> {
  // Orders Lists
  const ordersId_Raider_Orders = await db.orderLists.add({ userId, name: "Raider Orders", commands: ORDERS_Raider_Orders }) as number;
  const ordersId_Trooper_Orders = await db.orderLists.add({ userId, name: "Trooper Orders", commands: ORDERS_Trooper_Orders }) as number;
  const ordersId_Fortress_Orders = await db.orderLists.add({ userId, name: "Fortress Orders", commands: ORDERS_Fortress_Orders }) as number;
  const ordersId_Jay_Orders = await db.orderLists.add({ userId, name: "Jay Orders", commands: ORDERS_Jay_Orders }) as number;
  const ordersId_Speedy_Bot = await db.orderLists.add({ userId, name: "Speedy Bot", commands: ORDERS_Speedy_Bot }) as number;

  // Target Maps
  const mapId_Raider_Map = await db.targetMaps.add({ userId, name: "Raider Map", range: 2, grid: MAP_Raider_Map }) as number;
  const mapId_Trooper_Map = await db.targetMaps.add({ userId, name: "Trooper Map", range: 3, grid: MAP_Trooper_Map }) as number;
  const mapId_Fortress_Map = await db.targetMaps.add({ userId, name: "Fortress Map", range: 3, grid: MAP_Fortress_Map }) as number;
  const mapId_Speedy_Bomb = await db.targetMaps.add({ userId, name: "Speedy Bomb", range: 1, grid: MAP_Speedy_Bomb }) as number;

  // Bots
  const botId_Raider = await db.bots.add({
    userId,
    name:            "Raider",
    frame:           "Adult-bot = BF 40 slots, 50 ND, 650 weight, 500 cost.",
    engine:          "Nova-Engine = BE 18 slots, 9000 PO, 900 weight, 2700 cost.",
    computer:        "Newton-Computer = BC 1 slots, 25 CI, 0 weight, 250 cost.",
    armor:           "Tin-Plate = FA 10 slots, 100 AD, 300 weight, 200 cost.",
    sensor:          "Abstract_Thoughts = TS identifies Max 3 targets in 1 range, 30 PC, 1 slots, 30 weight, 150 cost.",
    weaponMaster:    "Phaser-Cannon = WM 60 WD, 3 WR, 6 slots, 600 PC, 600 weight, 1800 cost.",
    weaponSecondary: "Curved-Crowbar = WS 15 WD, 1 WR, 3 slots, 150 PC, 150 weight, 600 cost.",
    weaponBomb:      "NONE = WB 0,0 WD, 0 slot, PC 0 PC, 0 weight, 0 cost.",
    botImage:        "SmallBot",
    ordersListId:    ordersId_Raider_Orders,
    targetMapId:     mapId_Raider_Map,
    slotsUsed:       "39/40",
    totalWeight:     "2630",
    totalGold:       "6200",
    totalPower:      "780",
    move:            "3",
  }) as number;
  const botId_Trooper = await db.bots.add({
    userId,
    name:            "Trooper",
    frame:           "Master-bot = BF 45 slots, 60 ND, 780 weight, 600 cost.",
    engine:          "Tiger-Engine = BE 10 slots, 5000 PO, 500 weight, 1500 cost.",
    computer:        "Tesla-Computer = BC 1 slots, 45 CI, 0 weight, 450 cost.",
    armor:           "Aluminum-Plate = FA 25 slots, 250 AD, 600 weight, 500 cost.",
    sensor:          "Intense-Concentration = TS identifies Max 3 targets in 3 range, 80 PC, 3 slots, 80 weight, 400 cost.",
    weaponMaster:    "Laser-Cannon = WM 50 WD, 3 WR, 5 slots, 500 PC, 500 weight, 1500 cost.",
    weaponSecondary: "Rolled-Newspaper = WS 50 WD, 1 WR, 1 slot, 50 PC, 50 weight, 200 cost.",
    weaponBomb:      "NONE = WB 0,0 WD, 0 slot, PC 0 PC, 0 weight, 0 cost.",
    botImage:        "MedBot",
    ordersListId:    ordersId_Trooper_Orders,
    targetMapId:     mapId_Trooper_Map,
    slotsUsed:       "45/45",
    totalWeight:     "2510",
    totalGold:       "5150",
    totalPower:      "630",
    move:            "2",
  }) as number;
  const botId_Fortress = await db.bots.add({
    userId,
    name:            "Fortress",
    frame:           "Titan-bot = BF 60 slots, 90 ND, 1170 weight, 900 cost.",
    engine:          "Horse-Engine = BE 6 slots, 3000 PO, 300 weight, 900 cost.",
    computer:        "Aristotle-Computer = BC 1 slots, 35 CI, 0 weight, 350 cost.",
    armor:           "Adamantium-Plate = FA 40 slots, 400 AD, 900 weight, 800 cost.",
    sensor:          "Total-Awareness = TS identifies Max 1 targets in 3 range, 60 PC, 2 slots, 60 weight, 300 cost.",
    weaponMaster:    "Antimatter-Cannon = WM 90 WD, 5 WR, 9 slots, 900 PC, 900 weight, 2700 cost.",
    weaponSecondary: "Blunt-Sword = WS 10 WD, 1 WR, 2 slots, 100 PC, 100 weight, 400 cost.",
    weaponBomb:      "NONE = WB 0,0 WD, 0 slot, PC 0 PC, 0 weight, 0 cost.",
    botImage:        "BigBot",
    ordersListId:    ordersId_Fortress_Orders,
    targetMapId:     mapId_Fortress_Map,
    slotsUsed:       "60/60",
    totalWeight:     "3430",
    totalGold:       "6350",
    totalPower:      "1060",
    move:            "1",
  }) as number;
  const botId_Jay_Bomb = await db.bots.add({
    userId,
    name:            "Jay Bomb",
    frame:           "Junior-bot = BF 35 slots, 40 ND, 520 weight, 400 cost.",
    engine:          "Nova-Engine = BE 18 slots, 9000 PO, 900 weight, 2700 cost.",
    computer:        "Dohmer-Computer = BC 1 slots, 5 CI, 0 weight, 50 cost.",
    armor:           "Tin-Plate = FA 10 slots, 100 AD, 300 weight, 200 cost.",
    sensor:          "Blind-Night = TS identifies Max 1 targets in 1 range, 10 PC, 1 slots, 10 weight, 50 cost.",
    weaponMaster:    "Rubber-Hammer = WM 10 WD, 1 WR, 1 slot, 100 PC, 100 weight, 300 cost.",
    weaponSecondary: "NONE = WS 0 WD, 0 WR, 0 slot, 0 PC, 0 weight, 0 cost.",
    weaponBomb:      "Basement-Pounder = WB 350,175 WD, 7 slots, 0 PC, 350 weight, 1400 cost.",
    botImage:        "LargeBomb",
    ordersListId:    ordersId_Speedy_Bot,
    targetMapId:     mapId_Speedy_Bomb,
    slotsUsed:       "38/35",
    totalWeight:     "2180",
    totalGold:       "5100",
    totalPower:      "110",
    move:            "3",
  }) as number;
  const botId_Jay_Bot_2 = await db.bots.add({
    userId,
    name:            "Jay Bot 2",
    frame:           "Master-bot = BF 45 slots, 60 ND, 780 weight, 600 cost.",
    engine:          "Juggernaut-Engine = BE 14 slots, 7000 PO, 700 weight, 2100 cost.",
    computer:        "Dohmer-Computer = BC 1 slots, 5 CI, 0 weight, 50 cost.",
    armor:           "Copper-Plate = FA 15 slots, 150 AD, 400 weight, 300 cost.",
    sensor:          "Deep-Concentration = TS identifies Max 2 targets in 3 range, 70 PC, 3 slots, 70 weight, 350 cost.",
    weaponMaster:    "Antimatter-Cannon = WM 90 WD, 5 WR, 9 slots, 900 PC, 900 weight, 2700 cost.",
    weaponSecondary: "Rolled-Newspaper = WS 50 WD, 1 WR, 1 slot, 50 PC, 50 weight, 200 cost.",
    weaponBomb:      "NONE = WB 0,0 WD, 0 slot, PC 0 PC, 0 weight, 0 cost.",
    botImage:        "MedBigBot",
    ordersListId:    ordersId_Jay_Orders,
    targetMapId:     mapId_Fortress_Map,
    slotsUsed:       "43/45",
    totalWeight:     "2900",
    totalGold:       "6300",
    totalPower:      "1020",
    move:            "3",
  }) as number;

  // Armies
  await db.armies.add({ userId, name: "Raider Army", botIds: [botId_Raider, botId_Raider, botId_Raider, botId_Raider, botId_Raider, botId_Raider, botId_Raider, botId_Raider, botId_Raider, botId_Raider, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress] });
  await db.armies.add({ userId, name: "Trooper Army", botIds: [botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Raider, botId_Raider, botId_Raider, botId_Raider, botId_Raider] });
  await db.armies.add({ userId, name: "Fortress Army", botIds: [botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Raider, botId_Raider, botId_Raider, botId_Raider, botId_Raider, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper] });
  await db.armies.add({ userId, name: "Jay's Army", botIds: [botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Fortress, botId_Raider, botId_Raider, botId_Raider, botId_Raider, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Trooper, botId_Jay_Bomb, botId_Jay_Bomb, botId_Jay_Bomb] });
}
