#!/usr/bin/env node
/**
 * initiate-armies.js
 *
 * Reads scripts/army-data.json and regenerates src/db/userDefaults.ts.
 * Run with:  npm run initiate-armies
 *
 * Workflow:
 *   1. Edit scripts/army-data.json with the desired default armies, bots,
 *      orders lists, and targeting maps.
 *   2. Run:  npm run initiate-armies
 *   3. Run:  npm run build
 *   4. Deploy dist/ — new users get these defaults on first login.
 */

const fs   = require("fs");
const path = require("path");

const dataPath = path.join(__dirname, "army-data.json");
const outPath  = path.join(__dirname, "..", "src", "db", "userDefaults.ts");

// ── Load data ──────────────────────────────────────────────────────────────

const data = JSON.parse(fs.readFileSync(dataPath, "utf8"));
const { orderLists, targetMaps, bots, armies } = data;

// ── Validate references ────────────────────────────────────────────────────

const orderListNames = new Set(orderLists.map(o => o.name));
const targetMapNames = new Set(targetMaps.map(t => t.name));
const botNames       = new Set(bots.map(b => b.name));

let errors = 0;
for (const bot of bots) {
  if (!orderListNames.has(bot.ordersListName)) {
    console.error(`ERROR: Bot "${bot.name}" references unknown ordersListName "${bot.ordersListName}"`);
    errors++;
  }
  if (!targetMapNames.has(bot.targetMapName)) {
    console.error(`ERROR: Bot "${bot.name}" references unknown targetMapName "${bot.targetMapName}"`);
    errors++;
  }
}
for (const army of armies) {
  if (!Array.isArray(army.bots) || army.bots.length !== 20) {
    console.error(`ERROR: Army "${army.name}" must have exactly 20 bots (has ${army.bots?.length ?? 0})`);
    errors++;
  }
  for (const botName of (army.bots || [])) {
    if (!botNames.has(botName)) {
      console.error(`ERROR: Army "${army.name}" references unknown bot "${botName}"`);
      errors++;
    }
  }
}
if (errors > 0) {
  console.error(`\n${errors} error(s) found. Fix army-data.json and try again.`);
  process.exit(1);
}

// ── Build variable names ───────────────────────────────────────────────────

const san = s => s.replace(/[^a-zA-Z0-9]/g, "_");

// orders: ORDERS_<sanitized_name>
// targetMap: MAP_<sanitized_name>
// bot ids: botVar_<sanitized_name>
// orders ids: ordersVar_<sanitized_name>
// map ids: mapVar_<sanitized_name>

const ordersConst = name => `ORDERS_${san(name)}`;
const mapConst    = name => `MAP_${san(name)}`;
const ordersVar   = name => `ordersId_${san(name)}`;
const mapVar      = name => `mapId_${san(name)}`;
const botVar      = name => `botId_${san(name)}`;

// ── Generate TypeScript ────────────────────────────────────────────────────

const emptyGrid = () =>
  Array.from({ length: 7 }, () => Array(7).fill(""));

const lines = [];

lines.push(`import { db } from "./db";`);
lines.push(``);
lines.push(`// Auto-generated by scripts/initiate-armies.js — do not edit by hand.`);
lines.push(`// Edit scripts/army-data.json, then run: npm run initiate-armies`);
lines.push(``);

// Orders list constants
lines.push(`// === ORDERS LISTS ===`);
lines.push(``);
for (const ol of orderLists) {
  lines.push(`const ${ordersConst(ol.name)} = [`);
  for (const cmd of ol.commands) lines.push(`  ${JSON.stringify(cmd)},`);
  lines.push(`];`);
  lines.push(``);
}

// Target map grid constants (all start as empty 7x7)
lines.push(`// === TARGET MAP GRIDS ===`);
lines.push(``);
for (const tm of targetMaps) {
  const grid = tm.grid ?? emptyGrid();
  lines.push(`const ${mapConst(tm.name)}: string[][] = [`);
  for (const row of grid) lines.push(`  ${JSON.stringify(row)},`);
  lines.push(`];`);
  lines.push(``);
}

// seedUserDefaults function
lines.push(`// === SEED FUNCTION ===`);
lines.push(``);
lines.push(`export async function seedUserDefaults(userId: number): Promise<void> {`);

lines.push(`  // Orders Lists`);
for (const ol of orderLists) {
  lines.push(`  const ${ordersVar(ol.name)} = await db.orderLists.add({ userId, name: ${JSON.stringify(ol.name)}, commands: ${ordersConst(ol.name)} }) as number;`);
}
lines.push(``);

lines.push(`  // Target Maps`);
for (const tm of targetMaps) {
  lines.push(`  const ${mapVar(tm.name)} = await db.targetMaps.add({ userId, name: ${JSON.stringify(tm.name)}, range: ${tm.range}, grid: ${mapConst(tm.name)} }) as number;`);
}
lines.push(``);

lines.push(`  // Bots`);
for (const bot of bots) {
  lines.push(`  const ${botVar(bot.name)} = await db.bots.add({`);
  lines.push(`    userId,`);
  lines.push(`    name:            ${JSON.stringify(bot.name)},`);
  lines.push(`    frame:           ${JSON.stringify(bot.frame)},`);
  lines.push(`    engine:          ${JSON.stringify(bot.engine)},`);
  lines.push(`    computer:        ${JSON.stringify(bot.computer)},`);
  lines.push(`    armor:           ${JSON.stringify(bot.armor)},`);
  lines.push(`    sensor:          ${JSON.stringify(bot.sensor)},`);
  lines.push(`    weaponMaster:    ${JSON.stringify(bot.weaponMaster)},`);
  lines.push(`    weaponSecondary: ${JSON.stringify(bot.weaponSecondary)},`);
  lines.push(`    weaponBomb:      ${JSON.stringify(bot.weaponBomb)},`);
  lines.push(`    botImage:        ${JSON.stringify(bot.botImage)},`);
  lines.push(`    ordersListId:    ${ordersVar(bot.ordersListName)},`);
  lines.push(`    targetMapId:     ${mapVar(bot.targetMapName)},`);
  lines.push(`    slotsUsed:       ${JSON.stringify(bot.slotsUsed ?? "")},`);
  lines.push(`    totalWeight:     ${JSON.stringify(bot.totalWeight ?? "")},`);
  lines.push(`    totalGold:       ${JSON.stringify(bot.totalGold ?? "")},`);
  lines.push(`    totalPower:      ${JSON.stringify(bot.totalPower ?? "")},`);
  lines.push(`    move:            ${JSON.stringify(bot.move ?? "")},`);
  lines.push(`  }) as number;`);
}
lines.push(``);

lines.push(`  // Armies`);
for (const army of armies) {
  const ids = army.bots.map(name => botVar(name)).join(", ");
  lines.push(`  await db.armies.add({ userId, name: ${JSON.stringify(army.name)}, botIds: [${ids}] });`);
}

lines.push(`}`);
lines.push(``);

// ── Write output ───────────────────────────────────────────────────────────

fs.writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`✓ Wrote ${outPath}`);
console.log(`  ${orderLists.length} orders list(s), ${targetMaps.length} target map(s), ${bots.length} bot(s), ${armies.length} arm(ies)`);
